### ISSUE TITLE
Add ProSound mod by default

### ISSUE THREAD

**Issue by 8lall0** [MouseBiteLabs/Game-Boy-DMG-Color#1]
Hi,
i was thinkin' that adding by default the prosound mod on a pcb level would be a nice improvement.

For reference: https://guides.brit.co/guides/mod-your-dmg-gameboy-with-prosound-stereo-jack

That's with the help of an external audio jack, but can be done with internal jack too (i modded two DMGs with that, no issues)

**Comment by MouseBiteLabs** [comment]
The problem with doing that is you lose the amplification from the LM4853 for the headphones, so the max volume isn't as high as I would like it. That's why I added the solder pads so you could cut the traces and jumper to the potentiometer outputs if you wanted the speaker to still be amplified, but the headphone output to be the "pro-sound" quality.

Or if you wanted a second jack, you could just grab LOUT, ROUT, and GND from the pot just like in the link you sent!

![image](https://user-images.githubusercontent.com/97127539/188522059-d604602a-fad3-4a3f-8fbc-a323a46203b1.png)

**Comment by MouseBiteLabs** [comment]
Just an update - I was thinking about your comment more, and checked the site you linked again and realized you meant just adding a more convenient location for connection to a "pro-sound" headphone jack. So I've included that! Also working on a headphone board with an optional pro-sound headphone jack. New rev of boards should be arriving soon.

![image](https://user-images.githubusercontent.com/97127539/195855940-428fe03c-cd38-40bb-b7bb-958856a510b2.png)
