### ISSUE TITLE
LSDJ Specific - conflict with ips shortcuts

### ISSUE THREAD

**Issue by 8lall0** [MouseBiteLabs/Game-Boy-DMG-Color#2]
I use LSDJ to make music, and i was thinking that select+a+b is both an LSDJ action and the ips menu shortcut, probably there is a conflict that should at least be noted on the readme :)

**Comment by 8lall0** [comment]
Closing because i got confused, Sorry!

**Comment by MouseBiteLabs** [comment]
I can add a note for that definitely! I've never used that software before but adding the pro-sound output was partly motivated by users of LSDJ so I guess I should note it haha.

The only reason I used A/B/Sel is because that's the default the IPS kit uses.

It is worth noting that you don't *have* to use the A/B/Sel pads at the top of the board for the OSD menu. You could run longer wires down to the middle of the board and pick whatever buttons you want, I put pads for each button there for specifically that reason. You could do left, down, and A if you really wanted lol.
